apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - patches.yml
secretGenerator:
  - name: kratos-login-secrets
    files:
      - .env.local