apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-login
  template:
    spec:
      imagePullSecrets:
        - name: gcr-json-key

---
apiVersion: v1
kind: Service
metadata:
  name: kratos-login
spec:
  type: NodePort
  selector:
    app: kratos-login
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30031