apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: server
          image: eu.gcr.io/mmpt-233505/kratos-login
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: ORY_SDK_URL
              value: https://auth-dev.missmp.tech/
            - name: NEXT_PUBLIC_AFTER_LOGGED_IN_URL
              value: https://www.missmp.tech/
            - name: NEXT_PUBLIC_FORCE_COOKIE_DOMAIN
              value: missmp.tech
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
