apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - managedcertificate.yaml
  - ingress.yaml
  - frontendconfig.yaml
secretGenerator:
  - name: kratos-login-secrets
    files:
      - .env.local