apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-login
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: PORT
              value: "8080"
            - name: ORY_SDK_URL
              value: https://auth.dev.missmp.tech/
            - name: NEXT_PUBLIC_AFTER_LOGGED_IN_URL
              value: https://app.dev.missmp.tech/
            - name: NEXT_PUBLIC_FORCE_COOKIE_DOMAIN
              value: dev.missmp.tech