# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: tse"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos-login
  template:
    metadata:
      labels:
        app: kratos-login
    spec:
      containers:
        - name: server
          image: eu.gcr.io/mmpt-233505/kratos-login
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /app/.env.local
              subPath: .env.local
              name: secrets
      volumes:
        - name: secrets
          secret:
            secretName: kratos-login-secrets