# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: tse"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos-login
  template:
    metadata:
      labels:
        app: kratos-login
    spec:
      containers:
        - name: server
          image: eu.gcr.io/mmpt-233505/kratos-login
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: ORY_SDK_URL
              value: https://auth-dev.missmp.tech/
            - name: NEXT_PUBLIC_AFTER_LOGGED_IN_URL
              value: https://www.missmp.tech/
            - name: NEXT_PUBLIC_FORCE_COOKIE_DOMAIN
              value: missmp.tech
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
